{
 "title": "Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Grafana Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_bucket{status_code!=\"-1\"}[5m])) by (status_code)",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Percentage of Enabled Features",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(grafana_feature_toggles_info == 1) / count(grafana_feature_toggles_info) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Features On",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(grafana_feature_toggles_info == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feature Off",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(grafana_feature_toggles_info == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Grafana Go Routines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Request Latency (Group By Datasource)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grafana_datasource_request_duration_seconds_bucket[5m])) by (datasource, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Response Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grafana_datasource_response_size_bytes_bucket[5m])) by (datasource, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS By Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(grafana_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboard APP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres Auth Failed Attempts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({app=\"postgres\"} |= \"authentication\"[5m])"
      }
     ]
    },
    {
     "title": "# Reservations [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "sum by () (count_over_time({app=\"course-service\"} |json | message=\"booking reserved\" [5m]))"
      }
     ]
    },
    {
     "title": "Potential Sales [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
     "targets": [
      {
       "expr": "sum by () \n    (sum_over_time({app=\"course-service\"} \n        | json \n        | message=\"booking reserved\"\n        | unwrap price [5m]))"
      }
     ]
    },
    {
     "title": "# Logs Grouped by GRPC Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "sum by (grpc_code) (count_over_time({app=\"course-service\"} | json | message = \"finished call\" [1m]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "P95 API Request Latency (Grouped by status code)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "quantile_over_time(0.95, {app=\"course-service\"} \n    | json \n    | message =\"finished call\"\n    | unwrap grpc_time_ms [1m]) by (grpc_method, grpc_service)",
       "legendFormat": "{{grpc_service}}/{{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}